# Generated by Django 3.1.4 on 2020-12-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
    ]
