# Generated by Django 3.1.4 on 2020-12-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
