# Generated by Django 3.1.4 on 2021-01-02 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_created_date',
            field=models.DateTimeField(default=datetime.date(2021, 1, 2), null=True),
        ),
    ]
