# Generated by Django 3.1.4 on 2021-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0002_auto_20210102_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_created_date',
            field=models.DateField(default='2000-1-1', null=True),
        ),
    ]
