# Generated by Django 3.1.4 on 2020-12-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0002_auto_20201220_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
    ]
