# Generated by Django 3.1.4 on 2020-12-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0002_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_created_date',
            field=models.DateField(default=0, null=True),
        ),
    ]
