# Generated by Django 3.1.4 on 2020-12-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0003_remove_order_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
