# Generated by Django 3.1.4 on 2020-12-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0003_auto_20201224_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='delivery_date',
        ),
    ]
