# Generated by Django 3.1.4 on 2020-12-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0004_order_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
