# Generated by Django 3.1.4 on 2021-01-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0004_auto_20210102_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
