# Generated by Django 3.1.4 on 2020-12-24 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0004_remove_contract_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_created_date',
            field=models.DateField(default=datetime.date(1997, 10, 19), null=True),
        ),
    ]
