# Generated by Django 3.1.4 on 2021-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForestManagement', '0006_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
